### ISSUE TITLE
[Feature ⭐] 문자열 라이브러리 만들기

### ISSUE THREAD

**Issue by scarf005** [exciting-webserv/webserv#3]
### 종류

라이브러리

### 내용

(대충 파이썬에 있는 함수 만든다는 내용)

- [x] `split`
- [ ] `splitlines`
- [x] `trim`
- [x] `erase_from`

**Comment by cjeon42** [comment]
`trim`: `target`의 좌, 우에서 `charset`의 문자를 제거한다
프로토타입:
 `std::string &trim(std::string& target, const std::string& charset = " \t\v\r\n")` 
- [ ]  `trim`
